### ISSUE TITLE
Stuck on downloading the vole data

### ISSUE THREAD

**Issue by rvosa** [o-william-white/genome_skimming_pipeline#4]
Hi,

when I try to run the [code block about downloading example data](https://github.com/o-william-white/genome_skimming_pipeline#download-example-data) my miniconda doesn't like the arguments. What do you think might be going on?

```{bash}
$ conda env create -n sra-tools -c bioconda                                                                                    
usage: conda-env [-h] {create,export,list,remove,update,config} ...                                                                                                                   
conda-env: error: unrecognized arguments: -c    
```

**Comment by o-william-white** [comment]
I think this should be as follows: 
'''
conda create -n sra-tools -c bioconda sra-tools
'''
Away from my laptop but will confirm tomorrow.

**Comment by o-william-white** [comment]
Updated the README, thanks for highlight this.

**Comment by rvosa** [comment]
OK cool, that makes sense. With that sorted, I am now stuck on the actual downloading. Here's what I'm getting:

```
fetching reads for SRR5201684
2023-04-19T09:50:46 fastq-dump.2.8.0 sys: connection failed while opening file within cryptographic module - mbedtls_ssl_handshake returned -9984 ( X509 - Certificate verification failed, e.g. CRL, CA or signature check failed )
2023-04-19T09:50:46 fastq-dump.2.8.0 sys: mbedtls_ssl_get_verify_result returned 0x8 (  !! The certificate is not correctly signed by the trusted CA  )
2023-04-19T09:50:46 fastq-dump.2.8.0 err: item not found while constructing within virtual database module - the path 'SRR5201684' cannot be opened as database or table
```

So there's something wrong with validating the SSL certificates. This is on a virgin-ish Ubuntu 22.04LTS. I tried to update the certificates:

```
sudo apt-get update
sudo apt-get install --reinstall ca-certificates
sudo update-ca-certificates
```

And restarted the server, to no avail. Any idea how to fix that?

**Comment by o-william-white** [comment]
Not an error I have found before. Is it simply a network connection issue? I found this issue which seemed related https://github.com/ncbi/sra-tools/issues/139 

Also, it looks like conda has installed a sligtly older version or sra-tools. I wonder if using the most recent version might help? 
```
 conda create -n sra-tools -c bioconda sra-tools=3.0.3
```

**Comment by rvosa** [comment]
It is indeed a version issue: I Frankensteined fastq-dump onto the server using [NCBI's binaries](https://github.com/ncbi/sra-tools/wiki/02.-Installing-SRA-Toolkit) and then the download proceeds. When we try to do it the correct way via conda we seem to enter into dependency hell: it wants to update libgcc-ng and that seems like a scary thing to do.
